name: CI
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Print thing
      run: |
        echo "$FOO"
      env:
        FOO: ${{ secrets.FOO }}
