name: CI
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@267af2f1ed4911180b4bb25619ca4a586753cbd1
    - name: Print thing
      run: |
        scala-cli PrintEnv.sc -- FOO
      env:
        FOO: ${{ secrets.FOO }}
